spring.application.name=Value-Comparation
spring.data.mongodb.uri=mongodb+srv://PedroHenriqueS19:Franca1911@valuecomparison.6xg2ckz.mongodb.net/valuecomparison?appName=ValueComparison
api.security.token.secret=${JWT_SECRET:SenhaSecretaSuperForte123}
api.gemini.key=${GEMINI_API_KEY:COLE_AQUI_A_SUA_CHAVE_REAL_DO_GEMINI}
api.serp.key=${SERP_API_KEY:COLE_AQUI_A_SUA_CHAVE_REAL_DO_SERPAPI}