spring.application.name=Value-Comparation
spring.data.mongodb.uri=mongodb+srv://PedroHenriqueS19:Franca1911@valuecomparison.6xg2ckz.mongodb.net/valuecomparison?appName=ValueComparison
api.gemini.key=${GEMINI_API_KEY}
api.serp.key=${SERP_API_KEY}