spring.application.name=Value-Comparation
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/banco_local}
api.security.token.secret=${JWT_SECRET:SenhaSecretaSuperForte123}
api.gemini.key=${GEMINI_API_KEY:COLE_AQUI_A_SUA_CHAVE_REAL_DO_GEMINI}
api.serp.key=${SERP_API_KEY:COLE_AQUI_A_SUA_CHAVE_REAL_DO_SERPAPI}